// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.WindsorBot.subsystems;

import org.usfirst.frc4914.WindsorBot.RobotMap;
import org.usfirst.frc4914.WindsorBot.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Forklift extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon winchCAN = RobotMap.forkliftWinchCAN;
    private final SpeedController winchSlave = RobotMap.forkliftWinchSlave;
    private final CANTalon hookCAN = RobotMap.forkliftHookCAN;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // QE value at 54 inch height limit
    public static final double setpoint54 = -14;
    // QE value at maximum safe forklift height
    public static final double forkliftMax = -16;
    // QE value at maximum safe hook height
    public static final double hookMax = -0.5;
    // true when forklift operation restricted below 54 inches, false otherwise
    public boolean locked = true;

    public void initDefaultCommand() {
        setDefaultCommand(new OperateLift());
    }
    
    public double getFLiftQEValue() {
		return winchCAN.getEncPosition() / 10000.0;
	}

	public double getHookQEValue() {
		return hookCAN.getEncPosition() / 10000.0;
	}
	
	public void resetFLiftQE() {
		winchCAN.setEncPosition(0);
	}
	
	public void resetHookQE() {
		hookCAN.setEncPosition(0);
	}
	
	public void resetAllQEs() {
		resetFLiftQE();
		resetHookQE();
	}
	
	public void setFLift(double outputValue) {
		winchCAN.set(outputValue);
		winchSlave.set(outputValue);
	}
	
	public void setHook(double outputValue) {
		hookCAN.set(outputValue);
	}
	
	public void setBrake(boolean brake) {
		winchCAN.enableBrakeMode(brake);
		hookCAN.enableBrakeMode(brake);
	}
	
	public void stop() {
		setFLift(0);
		setHook(0);
	}
}