// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.WindsorBot.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4914.WindsorBot.Robot;
import org.usfirst.frc4914.WindsorBot.subsystems.Shooter;


public class OperateShooter extends Command {

	boolean intakeFinished = false;
	boolean highInit = true;
	boolean highFinished = false;
	
	public OperateShooter() {
		requires(Robot.shooter);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    protected void initialize() {
    }

    protected void execute() {
    	// intake binding to driver left trigger
    	if(Robot.oi.isDriverLT()) {
    		Robot.shooter.setIntake(1);
    		intakeFinished = true;
    	}
    	else if (!Robot.oi.isDriverLT() && intakeFinished) {
    		intakeFinished = false;
    		Robot.shooter.setIntake(-1);
    		Robot.shooter.setBottomFly(-0.8);
    		Timer.delay(0.3); // amount of time to push back down
    		Robot.shooter.stopFly();
    		Robot.shooter.stopIntake();
    	}
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    	Robot.shooter.stopFly();
    	Robot.shooter.stopIntake();
    }

    protected void interrupted() {
    	end();
    }
}